name: Deploy WordPress Theme to EC2

on:
  push:
    branches:
      - staging


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            --exclude=".git*" \
            --exclude="node_modules" \
            -e "ssh -i ~/.ssh/id_rsa" \
            ./ ${{ secrets.USER_NAME }}@${{ secrets.HOST_IP }}:/var/www/html/wp-content/themes/kctennisblast/
