name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - staging 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH key file
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key # Set correct permissions for the key file

    - name: SSH and deploy
      env:
        HOSTNAME: ${{ secrets.EC2_HOST }}
        USER_NAME: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
        # --- Deployment commands start here ---
        cd /path/to/your/app
        git pull origin main
        # e.g., restart your application service, run a build command, etc.
        # e.g., docker-compose build && docker-compose up -d
        # --- Deployment commands end here ---
        '
